name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSVC environment
      uses: microsoft/setup-msbuild@v1

    - name: Build DLL
      run: |
        cd ImageSearchDLL
        msbuild /t:Rebuild /p:Configuration=Release

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v2
      with:
        name: ImageSearchDLL
        path: ImageSearchDLL/bin/Release/*.dll
